version: "3"

services:
  nginx:
    build: ./requirements/nginx/
    networks:
      - network_for_wordpress
    volumes:
      - volume_for_wordpress:/var/www/html
    ports:
      - 443:443
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    networks:
      - network_for_wordpress
    volumes:
      - volume_for_mariadb:/var/lib/mariadb
    expose:
      - 3306
    restart: always
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    networks:
      - network_for_wordpress
    volumes:
      - volume_for_wordpress:/var/www/html
    expose:
      - 9000
    restart: always
    env_file:
      - .env
      
networks:
  network_for_wordpress:

volumes:
  volume_for_mariadb:
  volume_for_wordpress:
